### ISSUE TITLE
Hardware Set Up/Debugging/Firmware Update Application Software

### ISSUE THREAD

**Issue by jaidenfe** [jaidenfe/Lux#11]
A simplistic desktop application that will detect the Lux hardware and display information. Fields such as name, ip address, port number and network password will be able to be set/changed by the user. Information about the specific device (such as serial number, specs and firmware version) will be visible but not changeable by the user.

**Comment by JamesNorris** [comment]
Mostly complete: a3db54a

Still requires:
-Firmware version
-Hardware version
-Documentation

**Comment by JamesNorris** [comment]
Update:

Just needs documentation.

e5d1745

**Comment by jaidenfe** [comment]
This feature is depricated. The firmware now serves a webpage for configuration if it cannot connect to a network. Firmware updates should he handled over the air by the hub. Issue Resolved.
