### ISSUE TITLE
Website frontend

### ISSUE THREAD

**Issue by JamesNorris** [jaidenfe/Lux#6]
Need a simple website <b>Dashboard</b> for control of the devices.

- [x] On/Off for each Lux device
- [x] State indicator (on/off) display
- [x] Ability to group devices
- [ ] Ability to add a single device to multiple groups
- [x] Ability to rename a device (initial name is " LUX-" and the last few digits of the serial number)
- [x] The ability to retrieve this information to be sent to the server
- [x] "Apply" button to trigger the above

**Comment by jaidenfe** [comment]
<b>This is a carbon copy of my comments from pull request #31:</b>

>The home page is a little blank and I would suggest putting snap shots of what LUX is, how it works and maybe some pictures (trying to sell the product essentially).
>
>The about page is good, I would suggest adding more sections about the device itself and the network and why this is different from other smart light products.
>
>The log in is good, I do think we need to add a "sign up" button as well.
>
>Contact page is solid, maybe have a link to our github!
>
>The actual dashboard is sweet, I love the light! I do recommend restyling it using bootstrap at some point but for the initial release/prototype this is good! I would recommend making sure you can add a device to multiple groups and have a unique name. Also instead of having a "group name" make it "part of group(s)" then list the group names. Have groups come up as if they were devices themselves. Maybe have a separate "group" section. I would also suggest moving the light bulb on the right side of the button, we read left to right and it would make more sense to have the indicator after the state changing button. The "sign out" button should be in the top right portion of the page or under a "settings" hidden list. These are suggestions for the next release. The current implementation is good for our first release. It shows everything we need it to and allows us to change what we need to change, so good work!
>
>I would suggest updating the read me to adhere to our plan to have this running on the hub.
