### ISSUE TITLE
Fix WebServer Connection Crash

### ISSUE THREAD

**Issue by jaidenfe** [jaidenfe/Lux#60]
When the WebServer attempts to connect to the DeviceServer and can't connect it crashes the WebServer. This should be handled so that it waits a period of time and then attempts to reconnect. This should be repeated a number of times and then it should display a "Hub Disconnected" page with suggestions to fix this.

**Comment by kjwong2018** [comment]
The hot fix is in Jcnorris branch. Will look into merge conflict during break (hopefully) and pull into develop.

**Comment by kjwong2018** [comment]
The issue with the crash is when Flask is trying to connect with the server and its not up.
- Fix :  exception handler where it will break out of connect when such error occur and move on.

**Comment by jaidenfe** [comment]
Resolved
